### ISSUE TITLE
Advanced FPS Counter copyright infringement

### ISSUE THREAD

**Issue by DmitriyYukhanov** [JustinFincher/AReco#1]
Hey,

I'm Dmitriy Yukhanov, author of the Advanced FPS Counter plugin for Unity.

Thanks for purchasing Advanced FPS Counter and for using it in your project(s), I hope it goes well!
But unfortunately, it's not allowed to share it anywhere, as it violates Asset Store End User License Agreement (http://unity3d.com/legal/as_terms), sections 5 & 9 and my own copyrights.

And what is more upsetting, you have to totally vanish it from the repo, from all commits, which means you have to completely remove repo from the GitHub or make it private (which will cost you $7 / month) =(

I'll get back to you in few days to submit DMCA Takedown Notice if my asset will still be here.
Please, let me know if you need more time to resolve this issue!

I'm sorry and thank you for your understanding!

**Comment by JustinFincher** [comment]
Hi,
Thanks for this issue, I know the asset should not be shared and I do mention it in my repo README.md where I wrote:
> 因为使用了 Asset Store 上的第三方素材，某些素材的 license 不允许我们完全开源，因此在开源的时候删除了对应内容。
> (in English) because licenses of some 3rd party assets we used from Asset Store do not allow open source, so I removed content when uploading the repo.

And I just keep the `.meta` file of CodeStage folder, without leaking the source code, I hope you can check the repo content https://github.com/JustinFincher/AReco/tree/master/Assets, I only include the already open-sourced assets like UniRX, UnityARKitPlugin and MarkLight, not the commercial ones.

![image](https://user-images.githubusercontent.com/8359912/43361667-a559be9a-9307-11e8-9249-f25e1c015e32.png)

**Comment by JustinFincher** [comment]
@DmitriyYukhanov And if including `.meta` file is a violation too, I will remove the `.meta` file as well, I only include them because I want to keep the structure complete to anyone who wants to clone the project. Thanks!

**Comment by DmitriyYukhanov** [comment]
Hey, Justin!

Oh, that's my bad - the process is somewhat automated and I just overlooked you have only metas and not actual files.
Huge thanks for being proactive and avoiding copyrighted assets leaking to the public.
I'm sorry for the disturbance, .meta files are not violating anything.
